[[constraint]]
  name = "github.com/iotexproject/iotex-core"
  version = "v0.5.0-rc8"

[[constraint]]
  name = "github.com/iotexproject/iotex-address"
  revision = "6f79c578a9766e0caf7e5fd88613d48f59f00bb4"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  revision = "2bbee71fbe61def241832e800b4f0bd24d4beb89"
  source = "github.com/iotexproject/go-ethereum"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.9.0"
